project_id = "gcwbtfzkeyufkcdclhnz"

[functions.diagnosis-flow]
verify_jwt = false

[functions.agro-assist]
verify_jwt = false

[functions.treatment-engine]
verify_jwt = false

[functions.weather-advice]
verify_jwt = false
